"""
Input management package for Drone Hunter 2D.
"""
from src.input.input_manager import (
    InputManager,
    InputContext,
    ACTION_MOVE_X, ACTION_MOVE_Y, ACTION_AIM_ANGLE,
    ACTION_FIRE_PRIMARY, ACTION_FIRE_SECONDARY,
    ACTION_WEAPON_NEXT, ACTION_WEAPON_PREV,
    ACTION_ROLL, ACTION_EMP, ACTION_ULTIMATE,
    ACTION_SPECIAL, ACTION_PAUSE, ACTION_FULLSCREEN, ACTION_CLOAK,
    ACTION_CONFIRM, ACTION_CANCEL,
    ACTION_SECTOR_MAP, ACTION_HANGAR_BAY, ACTION_SETTINGS,
    ACTION_FRONT_TOP, ACTION_FRONT_BOTTOM, ACTION_CYCLE_CLASS,
    ACTION_WEAPON_SLOT_1, ACTION_WEAPON_SLOT_2, ACTION_WEAPON_SLOT_3,
    ACTION_WEAPON_SLOT_4, ACTION_WEAPON_SLOT_5, ACTION_WEAPON_SLOT_6,
    ACTION_SELECT_SLOT_1, ACTION_SELECT_SLOT_2, ACTION_SELECT_SLOT_3,
    ACTION_SELECT_SLOT_4, ACTION_SELECT_SLOT_5,
    DEVICE_KEYBOARD_MOUSE, DEVICE_GAMEPAD, DEVICE_JOYSTICK
)
